name: woocommerce_flutter_api
description: A Flutter package for WooCommerce integration. Manage products, orders, and customers with updated dependencies for seamless e-commerce.
version: 1.0.2
repository: https://github.com/loaidev64/woocommerce_flutter_api.git
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  dio: ^5.4.1
  faker: ^2.1.0
  flutter_secure_storage: ^9.0.0
  pretty_dio_logger: ^1.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
